on: [pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v3

      - name: Build App
        run: npx prettier . --check
